export const statistics = {
  lastSevenDays: {
    orders: 10,
    revenue: 1000,
    newUsers: 3,
    latestOrders: [
      {
        id: "01",
        status: "pending",
        name: "Dr. Muhammad Yunus",
        amount: "100",
        items: "1",
      },
      {
        id: "02",
        status: "pending",
        name: "Shonto Larma",
        amount: "100",
        items: "1",
      },
      {
        id: "03",
        status: "shipped",
        name: "Zulkarnaine Saer",
        amount: "100",
        items: "1",
      },
      {
        id: "04",
        status: "canceled",
        name: "Mr Chika Khan",
        amount: "100",
        items: "1",
      },
      {
        id: "05",
        status: "shipped",
        name: "Bill Gates",
        amount: "100",
        items: "1",
      },
    ],
    latestProducts: [
      {
        id: 1,
        name: "Diabit food supplement",
        category: "Health",
        price: 1200,
        stock: 35,
        sales: 82,
      },
      {
        id: 2,
        name: "SmartWatch X2",
        category: "Electronics",
        price: 4500,
        stock: 12,
        sales: 154,
      },
      {
        id: 3,
        name: "Keto Bar soap",
        category: "Health",
        price: 150,
        stock: 150,
        sales: 98,
      },
      {
        id: 4,
        name: "Noise Cancelling Headphones",
        category: "Electronics",
        price: 7000,
        stock: 5,
        sales: 64,
      },
      {
        id: 5,
        name: "Organic Green Tea",
        category: "Beverage",
        price: 300,
        stock: 60,
        sales: 120,
      },
    ],
  },
  lastThirtyDays: {
    orders: 15,
    revenue: 1500,
    newUsers: 5,
    latestOrders: [
      { status: "pending", name: "Ashik Hossain", amount: "100", items: "1" },
      {
        status: "pending",
        name: "Biswanath Sharma",
        amount: "100",
        items: "1",
      },
      { status: "shipped", name: "Leonardo Messi", amount: "100", items: "1" },
      { status: "canceled", name: "Mr Chika Khan", amount: "100", items: "1" },
      { status: "shipped", name: "Zeff Bejos", amount: "100", items: "1" },
    ],
    latestProducts: [
      {
        id: 6,
        name: "Portable Blender",
        category: "Appliances",
        price: 2200,
        stock: 23,
        sales: 47,
      },
      {
        id: 7,
        name: "Vitamin C Serum",
        category: "Beauty",
        price: 800,
        stock: 40,
        sales: 73,
      },
      {
        id: 8,
        name: "Yoga Mat Pro",
        category: "Fitness",
        price: 1800,
        stock: 10,
        sales: 88,
      },
      {
        id: 9,
        name: "Herbal Shampoo",
        category: "Beauty",
        price: 550,
        stock: 35,
        sales: 45,
      },
      {
        id: 10,
        name: "Wireless Earbuds",
        category: "Electronics",
        price: 3200,
        stock: 8,
        sales: 104,
      },
    ],
  },
  lastNinetyDays: {
    orders: 23,
    revenue: 2300,
    newUsers: 8,
    latestOrders: [
      { status: "pending", name: "Afzal Hossain" },
      { status: "pending", name: "Biswanath Sharma" },
      { status: "shipped", name: "Anzo Fernandez" },
      { status: "canceled", name: "Mr Chika Khan" },
      { status: "shipped", name: "Bill Gates" },
    ],
    latestProducts: [
      {
        id: 11,
        name: "Resistance Bands Set",
        category: "Fitness",
        price: 900,
        stock: 22,
        sales: 61,
      },
      {
        id: 12,
        name: "Matcha Powder",
        category: "Beverage",
        price: 500,
        stock: 17,
        sales: 34,
      },
      {
        id: 13,
        name: "Electric Kettle",
        category: "Appliances",
        price: 2500,
        stock: 14,
        sales: 39,
      },
      {
        id: 14,
        name: "Face Roller",
        category: "Beauty",
        price: 650,
        stock: 30,
        sales: 28,
      },
      {
        id: 15,
        name: "Smart Scale",
        category: "Fitness",
        price: 3800,
        stock: 6,
        sales: 56,
      },
    ],
  },
};
